#!/usr/bin/env python3
"""Generate matching ESP8266 and Swift weather icon bitmaps.

Input files are the QWeather Icons v1.8.0 SVGs listed in ICONS. The SVGs are
rasterized by macOS `sips`, inset into a 48px canvas, then reduced to a 1-bit
mask so the firmware can tint them without carrying a full icon font.
"""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw


ICON_SIZE = 48
CONTENT_SIZE = 44
ROW_BYTES = ICON_SIZE // 8

ICONS = (
    ("clear_day", "clearDay", "100-fill.svg", "100"),
    ("clear_night", "clearNight", "150-fill.svg", "150"),
    ("partly_day", "partlyDay", "103-fill.svg", "103"),
    ("partly_night", "partlyNight", "153-fill.svg", "153"),
    ("cloudy", "cloudy", "104-fill.svg", "104"),
    ("light_rain", "lightRain", "305-fill.svg", "305"),
    ("moderate_rain", "moderateRain", "306-fill.svg", "306"),
    ("heavy_rain", "heavyRain", "307-fill.svg", "307"),
    ("storm_rain", "stormRain", "310-fill.svg", "310"),
    ("light_snow", "lightSnow", "400-fill.svg", "400"),
    ("moderate_snow", "moderateSnow", "401-fill.svg", "401"),
    ("heavy_snow", "heavySnow", "402-fill.svg", "402"),
    ("fog", "fog", "501-fill.svg", "501"),
    ("haze", "haze", "502-fill.svg", "502"),
    ("dust", "dust", "504-fill.svg", "504"),
    ("wind", "wind", "2208.svg", "2208"),
    ("unknown", "unknown", "999-fill.svg", "999"),
)


def rasterize(svg: Path, work_dir: Path) -> Image.Image:
    png = work_dir / f"{svg.stem}.png"
    subprocess.run(
        ["sips", "-z", "256", "256", "-s", "format", "png", str(svg), "--out", str(png)],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
    )
    alpha = Image.open(png).convert("RGBA").getchannel("A")
    alpha = alpha.resize((CONTENT_SIZE, CONTENT_SIZE), Image.Resampling.LANCZOS)
    canvas = Image.new("L", (ICON_SIZE, ICON_SIZE), 0)
    inset = (ICON_SIZE - CONTENT_SIZE) // 2
    canvas.paste(alpha, (inset, inset))
    return canvas.point(lambda value: 255 if value >= 64 else 0, mode="1")


def bitmap_bytes(mask: Image.Image) -> bytes:
    data = bytearray()
    pixels = mask.load()
    for y in range(ICON_SIZE):
        for byte_x in range(ROW_BYTES):
            value = 0
            for bit in range(8):
                if pixels[byte_x * 8 + bit, y]:
                    value |= 0x80 >> bit
            data.append(value)
    return bytes(data)


def format_bytes(data: bytes, indent: str) -> str:
    rows = []
    for start in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02x}" for value in data[start : start + 16])
        rows.append(f"{indent}{values},")
    return "\n".join(rows)


def write_firmware(path: Path, bitmaps: list[bytes]) -> None:
    flattened = b"".join(bitmaps)
    enum_values = "\n".join(
        f"  WEATHER_ICON_{name.upper()} = {index},"
        for index, (name, _, _, _) in enumerate(ICONS)
    )
    source_codes = ", ".join(code for _, _, _, code in ICONS)
    content = f"""#pragma once
#include <Arduino.h>

// QWeather Icons v1.8.0, icon design licensed CC BY 4.0.
// Rasterized, inset and reduced to 1-bit. Source icon codes: {source_codes}.
#define WEATHER_ICON_W {ICON_SIZE}
#define WEATHER_ICON_H {ICON_SIZE}
#define WEATHER_ICON_ROW_BYTES {ROW_BYTES}
#define WEATHER_ICON_BYTES (WEATHER_ICON_ROW_BYTES * WEATHER_ICON_H)
#define WEATHER_ICON_COUNT {len(ICONS)}

enum WeatherIconIndex {{
{enum_values}
}};

const uint8_t WEATHER_ICON_BITMAPS[WEATHER_ICON_COUNT * WEATHER_ICON_BYTES] PROGMEM = {{
{format_bytes(flattened, "  ")}
}};
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii")


def write_swift(path: Path, bitmaps: list[bytes]) -> None:
    flattened = b"".join(bitmaps)
    cases = "\n".join(
        f"    case {swift_name} = {index}"
        for index, (_, swift_name, _, _) in enumerate(ICONS)
    )
    source_codes = ", ".join(code for _, _, _, code in ICONS)
    content = f"""// Generated by tools/generate_weather_icons.py.
// QWeather Icons v1.8.0, icon design licensed CC BY 4.0.
// Rasterized, inset and reduced to 1-bit. Source icon codes: {source_codes}.

enum WeatherIconKind: Int {{
{cases}
}}

enum WeatherIconData {{
    static let width = {ICON_SIZE}
    static let height = {ICON_SIZE}
    static let rowBytes = {ROW_BYTES}
    static let bytesPerIcon = rowBytes * height

    static let bytes: [UInt8] = [
{format_bytes(flattened, "        ")}
    ]

    static func isSet(_ kind: WeatherIconKind, x: Int, y: Int) -> Bool {{
        let offset = kind.rawValue * bytesPerIcon + y * rowBytes + x / 8
        return bytes[offset] & (0x80 >> UInt8(x % 8)) != 0
    }}
}}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii")


def write_preview(path: Path, masks: list[Image.Image]) -> None:
    columns = 5
    cell_w, cell_h = 96, 80
    rows = (len(masks) + columns - 1) // columns
    preview = Image.new("RGB", (columns * cell_w, rows * cell_h), "#eef2ef")
    draw = ImageDraw.Draw(preview)
    for index, (mask, (_, _, _, code)) in enumerate(zip(masks, ICONS)):
        x = (index % columns) * cell_w
        y = (index // columns) * cell_h
        icon = Image.new("RGB", mask.size, "#eef2ef")
        icon.paste("#087e68", mask=mask)
        preview.paste(icon, (x + 24, y + 4))
        draw.text((x + 8, y + 56), code, fill="#10201c")
    path.parent.mkdir(parents=True, exist_ok=True)
    preview.save(path)


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="directory containing the selected QWeather SVGs")
    parser.add_argument(
        "--firmware",
        type=Path,
        default=repo / "firmware/include/img/weather_icons.h",
    )
    parser.add_argument(
        "--swift",
        type=Path,
        default=repo / "mac-app/Sources/AIClockBridge/WeatherIconData.swift",
    )
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()

    missing = [filename for _, _, filename, _ in ICONS if not (args.source / filename).is_file()]
    if missing:
        parser.error(f"missing SVG files: {', '.join(missing)}")

    with tempfile.TemporaryDirectory(prefix="aiclock-weather-icons-") as temp:
        masks = [rasterize(args.source / filename, Path(temp)) for _, _, filename, _ in ICONS]
    bitmaps = [bitmap_bytes(mask) for mask in masks]
    write_firmware(args.firmware, bitmaps)
    write_swift(args.swift, bitmaps)
    if args.preview:
        write_preview(args.preview, masks)
    print(f"generated {len(ICONS)} icons, {len(b''.join(bitmaps))} bytes per target")


if __name__ == "__main__":
    main()
